#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v27
# autospec commit: 65cf152
#
Name     : R-CircStats
Version  : 0.2.7
Release  : 54
URL      : https://ftp.osuosl.org/pub/cran/src/contrib/CircStats_0.2-7.tar.gz
Source0  : https://ftp.osuosl.org/pub/cran/src/contrib/CircStats_0.2-7.tar.gz
Summary  : Circular Statistics, from "Topics in Circular Statistics" (2001)
Group    : Development/Tools
License  : GPL-2.0
Requires: R-CircStats-license = %{version}-%{release}
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
(2001) S. Rao Jammalamadaka and A. SenGupta, World Scientific.

%package license
Summary: license components for the R-CircStats package.
Group: Default

%description license
license components for the R-CircStats package.


%prep
%setup -q -n CircStats
pushd ..
cp -a CircStats buildavx2
popd
pushd ..
cp -a CircStats buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1750431182

%install
export SOURCE_DATE_EPOCH=1750431182
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/R-CircStats
cp %{_builddir}/CircStats/COPYING %{buildroot}/usr/share/package-licenses/R-CircStats/1e9957deb8536846f32703e08a5332116b0d3660 || :
cp %{_builddir}/CircStats/inst/COPYRIGHTS %{buildroot}/usr/share/package-licenses/R-CircStats/48c3b98d1f5f9d9d9a51a9674065163652e88276 || :
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library
mkdir -p %{buildroot}-v3/usr/lib64/R/library
mkdir -p %{buildroot}-v4/usr/lib64/R/library
mkdir -p %{buildroot}-va/usr/lib64/R/library

mkdir -p ~/.R
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL  --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}-v3/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize  -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --preclean  --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}-v4/usr/lib64/R/library .
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean  --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/CircStats/COPYRIGHTS
/usr/lib64/R/library/CircStats/DESCRIPTION
/usr/lib64/R/library/CircStats/INDEX
/usr/lib64/R/library/CircStats/Meta/Rd.rds
/usr/lib64/R/library/CircStats/Meta/data.rds
/usr/lib64/R/library/CircStats/Meta/features.rds
/usr/lib64/R/library/CircStats/Meta/hsearch.rds
/usr/lib64/R/library/CircStats/Meta/links.rds
/usr/lib64/R/library/CircStats/Meta/nsInfo.rds
/usr/lib64/R/library/CircStats/Meta/package.rds
/usr/lib64/R/library/CircStats/NAMESPACE
/usr/lib64/R/library/CircStats/R/CircStats
/usr/lib64/R/library/CircStats/R/CircStats.rdb
/usr/lib64/R/library/CircStats/R/CircStats.rdx
/usr/lib64/R/library/CircStats/data/rao.table.rda
/usr/lib64/R/library/CircStats/help/AnIndex
/usr/lib64/R/library/CircStats/help/CircStats.rdb
/usr/lib64/R/library/CircStats/help/CircStats.rdx
/usr/lib64/R/library/CircStats/help/aliases.rds
/usr/lib64/R/library/CircStats/help/paths.rds
/usr/lib64/R/library/CircStats/html/00Index.html
/usr/lib64/R/library/CircStats/html/R.css

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/R-CircStats/1e9957deb8536846f32703e08a5332116b0d3660
/usr/share/package-licenses/R-CircStats/48c3b98d1f5f9d9d9a51a9674065163652e88276
